gravitee-io/gravitee-policy-groovy

README.adoc
src/main/java/io/gravitee/policy/groovy/GroovyPolicy.java
src/main/java/io/gravitee/policy/groovy/configuration/GroovyPolicyConfiguration.java
src/main/resources/schemas/policy-schema-form.json

feat(groovy): Add the on-request-content handler

---

pom.xml
src/main/java/io/gravitee/policy/groovy/model/ContentAwareRequest.java

fix(gateway): Update model to handle multiple values per query parameter

---

README.adoc
pom.xml
src/main/java/io/gravitee/policy/groovy/GroovyPolicy.java

This closes gravitee-io/issues#913

Bind the result on the context for the onRequestContent/onResponseContent scripts

---

src/main/java/io/gravitee/policy/groovy/GroovyPolicy.java

fix(groovy): Add missing variables into onRequest / onResponse scripts

---

pom.xml
src/main/java/io/gravitee/policy/groovy/model/ContentAwareRequest.java

And move dependency to Gravitee EL
Closes gravitee-io/issues#1987

chore: Remove deprecated Gateway EL module

---

src/main/java/io/gravitee/policy/groovy/GroovyPolicy.java
src/main/java/io/gravitee/policy/groovy/utils/AttributesBasedExecutionContext.java

feat(dictionary): add support

---

pom.xml
src/main/java/io/gravitee/policy/groovy/utils/AttributesBasedExecutionContext.java
src/test/java/io/gravitee/policy/groovy/GroovyPolicyTest.java
src/test/resources/io/gravitee/policy/groovy/break_request.groovy
src/test/resources/io/gravitee/policy/groovy/invalid_script.groovy
src/test/resources/io/gravitee/policy/groovy/modify_response_headers.groovy
src/test/resources/io/gravitee/policy/groovy/set_context_attribute.groovy

Some unit tests have been added.
Closes gravitee-io/issues#2455

fix(groovy): Set the attribute based context as a context decorator.

---

pom.xml
src/main/java/io/gravitee/policy/groovy/GroovyPolicy.java
src/test/java/io/gravitee/policy/groovy/GroovyPolicyTest.java
src/test/resources/io/gravitee/policy/groovy/read_json.groovy
src/test/resources/io/gravitee/policy/groovy/read_json.json

Closes gravitee-io/issues#2717

fix(groovy): Change the classloader used to load the FastStringService

---

src/main/java/io/gravitee/policy/groovy/GroovyPolicy.java
src/test/java/io/gravitee/policy/groovy/GroovyPolicyTest.java

fix: Better management of memory consumption

---

README.adoc
pom.xml
src/main/java/io/gravitee/policy/groovy/GroovyInitializer.java
src/main/java/io/gravitee/policy/groovy/GroovyPolicy.java
src/main/java/io/gravitee/policy/groovy/sandbox/SecuredAnnotationCustomizer.java
src/main/java/io/gravitee/policy/groovy/sandbox/SecuredGroovyShell.java
src/main/java/io/gravitee/policy/groovy/sandbox/SecuredInterceptor.java
src/main/java/io/gravitee/policy/groovy/sandbox/SecuredResolver.java
src/main/resources/groovy-whitelist
src/test/java/io/gravitee/policy/groovy/GroovyPolicyTest.java
src/test/java/io/gravitee/policy/groovy/sandbox/SecuredGroovyShellTest.java
src/test/resources/logback-test.xml

Depends on gravitee-io/issues#3935
Closes gravitee-io/issues#3933
Closes gravitee-io/issues#4050

feat(sandbox): sandbox Groovy shell

---

pom.xml
src/main/java/io/gravitee/policy/groovy/sandbox/SecuredResolver.java
src/test/java/io/gravitee/policy/groovy/sandbox/SecuredGroovyShellTest.java

fix(getat): problem invoking array.getAt(int)

---

src/main/java/io/gravitee/policy/groovy/sandbox/SecuredResolver.java
src/test/java/io/gravitee/policy/groovy/sandbox/SecuredGroovyShellTest.java
src/test/resources/logback-test.xml

fix(array): allow array length usage

---

.circleci/config.yml
pom.xml
src/main/java/io/gravitee/policy/groovy/model/ContentAwareRequest.java
src/main/java/io/gravitee/policy/groovy/model/ContentAwareResponse.java

Related to gravitee-io/issues#5220

chore(vertx4): move to gravitee-bom and use vertx4.

---

pom.xml
src/main/resources/groovy-whitelist
src/test/java/io/gravitee/policy/groovy/GroovyPolicyTest.java
src/test/resources/io/gravitee/policy/groovy/read_xml.groovy
src/test/resources/io/gravitee/policy/groovy/read_xml.xml

feat(xml): add xml support

---

src/main/resources/schemas/policy-schema-form.json

feat: hide form fields based on scope context

---

src/main/resources/groovy-whitelist

fix(am): adapt AM safe model objects

---

.prettierignore
pom.xml
src/main/java/org/kohsuke/groovy/sandbox/SandboxTransformer.java
src/main/resources/groovy-whitelist

chore: add support for Java 17 and move to groovy 3

---

pom.xml
src/main/java/io/gravitee/policy/groovy/model/ContentAwareRequest.java
src/main/java/io/gravitee/policy/groovy/model/ContentAwareResponse.java
src/main/java/io/gravitee/policy/groovy/model/HeaderMapAdapter.java
src/main/java/io/gravitee/policy/groovy/utils/AttributesBasedExecutionContext.java
src/test/java/io/gravitee/policy/groovy/GroovyPolicyTest.java

Closes gravitee-io/issues#6772

feat(headers): Internal rework and introduce HTTP Headers API

---

pom.xml
src/main/java/io/gravitee/policy/groovy/sandbox/SecuredResolver.java
src/main/resources/groovy-whitelist
src/test/java/io/gravitee/policy/groovy/GroovyPolicyTest.java
src/test/java/io/gravitee/policy/groovy/sandbox/SecuredGroovyShellTest.java
src/test/resources/io/gravitee/policy/groovy/iterate_on_map.groovy
src/test/resources/io/gravitee/policy/groovy/iterate_on_map.json
src/test/resources/io/gravitee/policy/groovy/play_with_strings.groovy

**Issue**
https://github.com/gravitee-io/issues/issues/7302
---
**Gravitee.io Automatic Deployment**
🚀 A prerelease version of this package has been published on Gravitee's private artifactory, you can:
- use it directly by updating your project with version: `2.2.0-SNAPSHOT.7302-fix-map-iteration`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-groovy/2.2.0-SNAPSHOT.7302-fix-map-iteration/gravitee-policy-groovy-2.2.0-SNAPSHOT.7302-fix-map-iteration.zip)

Fix map/string whitelist

---

CHANGELOG.md
pom.xml
src/main/java/io/gravitee/policy/groovy/model/BindableExecutionContext.java
src/main/java/io/gravitee/policy/groovy/model/http/BindableHttpRequest.java
src/main/java/io/gravitee/policy/groovy/utils/AttributesBasedExecutionContext.java
src/main/resources/groovy-whitelist
src/test/java/io/gravitee/policy/groovy/GroovyPolicyTest.java

**Description**
Merge 'alpha' into master

Merge 'alpha' into master
